AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Stackery Serverless API Example Stack
Resources:
  api:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub
        - ${ResourceName} From Stackery Stack ${StackeryStackTagName} Environment ${StackeryEnvironmentTagName}
        - ResourceName: api
      StageName: !Ref StackeryEnvironmentAPIGatewayStageName
      DefinitionBody:
        swagger: '2.0'
        info: {}
        paths:
          /lookup:
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${lookup.Arn}/invocations
              responses: {}
      EndpointConfiguration: REGIONAL
  lookup:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-lookup
      Description: !Sub
        - Stackery Stack ${StackeryStackTagName} Environment ${StackeryEnvironmentTagName} Function ${ResourceName}
        - ResourceName: lookup
      CodeUri: src/lookup
      Handler: index.handler
      Runtime: nodejs12.x
      MemorySize: 1024
      Timeout: 15
      Tracing: Active
      Policies:
        - AWSXrayWriteOnlyAccess
      Events:
        apiGETlookup:
          Type: Api
          Properties:
            Path: /lookup
            Method: GET
            RestApiId: !Ref api
      Layers:
        - !Ref GeoIPDataLambdaLayer
    Metadata:
      StackeryName: lookup
  GeoIPDataLambdaLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: GeoIPDataLambdaLayer
      Description: Geo IP Data Lambda Layer containing free maxmind database
      ContentUri: src/geoIPDataLambdaLayer
      CompatibleRuntimes:
        - python3.6
        - python3.7
        - nodejs12.x
        - nodejs10.x
      LicenseInfo: MIT
      RetentionPolicy: Retain
Parameters:
  StackeryStackTagName:
    Type: String
    Description: Stack Name (injected by Stackery at deployment time)
  StackeryEnvironmentTagName:
    Type: String
    Description: Environment Name (injected by Stackery at deployment time)
  StackeryEnvironmentAPIGatewayStageName:
    Type: String
    Description: Environment name used for API Gateway Stage names (injected by Stackery at deployment time)
